.TH "gt-1.0" "1" "September 2019" "gt-1.0" "User manual"
.SH NAME
gt-1.0 \- BASH script to manage your ssh connections.
.SH DESCRIPTION
.B GT
stands for Go To some server via SSH.
.nf
It builds menu (via dialog) from your ~/.ssh/config.
Can run commands, copy files, tunnel ports and connect.
Your commands can be easily added to the commands list.
Just edit this part of the script:

cmdlist_renew () { cmdlist=(
    #Command#  #Description#
    "ls  \-la"  "List Files."
    "free \-h"  "Show free memory."
    "df  \-ih"  "Show free inodes."
    "df   \-h"  "Show free disk space."
    ""         ""
    "Info"     "Full system info."
    "Copy"     "Copy selected file or dir."
    "Sshkey"   "Add my ssh key to this server."
    "Alias"    "Add my usefull aliases to this server."
    ""         ""
    "Local"    "Change local  port $LOCAL"
    "Remote"   "Change remote port $REMOTE"
    "Tunnel"   "Start portunneling from $target's port $REMOTE to local port $LOCAL"
); }

Or override this list and $LOCAL|$REMOTE|$timer vars in confile ~/.gtrc

First collumn - command, second - description.
Simple commands like 'ls \-la' can be added as is.
A list of commands or a complicated logic better add via function.
Empty string is used as a delimiter.

You can add hosts description(in ~/.ssh/config) like this:
Host server1 #DESCRIPTION
HostName 192.168.0.1
Port 22
User admin

You can add menu delimiters(in ~/.ssh/config) like this:
#Host DUMMY #TEXT#

You can customize dialog colors by creating a config file:
dialog \-\-create-rc ~/.dialogrc

.B SSH config exampple
#Host DUMMY #Rybinsk#

Host rybserver1 #First server
HostName 192.168.0.1
Port 22
User user

Host rybserver2 #Second server
HostName 192.168.0.2
Port 222
User user

Host rybserver3 #Third server
HostName 192.168.0.3
User user

#Host DUMMY #Moscow#

Host moserver1 #First server
HostName 192.169.0.1
Port 22
User admin

Host moserver2 #Second server
HostName 192.169.0.2
User admin

Host moserver3 #Third server
HostName 192.169.0.3
User admin

.SH AUTHOR
Ivan Marov <ie.marov@gmail.com>
.SH GITHUB
https://github.com/vaniacer/sshto
